apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:        # ✅ fixed typo (was matchLables)
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: deploy-container   # ✅ fixed typo (was depoy-container)
        image: thangamec0312/todayimage
        ports:
        - containerPort: 80      # ✅ removed extra space before containerPort

